"""Internal mail-gog writer: emit a Markdown preview and a frozen delivery script."""

from __future__ import annotations

import html
import json
import shlex
import sys
from email.parser import BytesParser
from email.policy import default
from pathlib import Path
from typing import Any

import mime


def markdown_value(value: str) -> str:
    value = html.escape(value, quote=False)
    for character in ("\\", "`", "*", "_", "[", "]"):
        value = value.replace(character, "\\" + character)
    return value


def preview(raw: bytes, manifest: dict[str, Any]) -> str:
    message = BytesParser(policy=default).parsebytes(raw)
    lines = ["# " + markdown_value(str(message.get("Subject", "(no subject)"))), ""]
    lines.append("- From: " + markdown_value(str(message["From"])))
    lines.append("- Account: " + markdown_value(manifest["account"]))
    for name in ("To", "Cc", "Bcc"):
        if message.get(name):
            lines.append(f"- {name}: " + markdown_value(str(message[name])))
    delivery = "Send"
    if manifest.get("delivery") == "draft":
        delivery = "Update draft " + manifest["draft_id"] if manifest.get("draft_id") else "Create draft"
    lines.append("- Delivery: " + markdown_value(delivery))
    attachments = []
    for part in message.walk():
        if part.is_multipart() or part.get_content_disposition() not in ("attachment", "inline"):
            continue
        size = len(part.get_payload(decode=True) or b"")
        name = markdown_value(part.get_filename() or "Unnamed attachment")
        label = "inline" if part.get_content_disposition() == "inline" else "attachment"
        attachments.append(f"  - {name} ({part.get_content_type()}, {size} bytes, {label})")
    lines.append("- Attachments:" if attachments else "- Attachments: None")
    lines.extend(attachments)
    body = mime.body_content(message, "plain")
    if body is None:
        raise ValueError("the finalized message has no plain-text preview")
    return "\n".join(lines) + "\n\n---\n\n" + body


def delivery_script(manifest: dict[str, Any], request: dict[str, Any]) -> str:
    method = "gmail.users.messages.send"
    params = {"userId": "me"}
    body = request
    if manifest.get("delivery") == "draft":
        method = "gmail.users.drafts.create"
        body = {"message": request}
        if manifest.get("draft_id"):
            method = "gmail.users.drafts.update"
            params["id"] = manifest["draft_id"]
    # A single-line JSON payload cannot collide with the heredoc terminator.
    payload = json.dumps(body, ensure_ascii=True, separators=(",", ":"))
    return "\n".join([
        "#!/bin/sh",
        "# Generated by Quarto Mail. Running this script performs the configured delivery.",
        "set -eu",
        'if [ "$#" -ne 0 ]; then echo "Usage: sh MESSAGE.send.sh" >&2; exit 2; fi',
        "umask 077",
        'request=$(mktemp "${TMPDIR:-/tmp}/quarto-mail-send.XXXXXX")',
        "trap 'rm -f \"$request\"' EXIT",
        "trap 'exit 130' INT",
        "trap 'exit 143' TERM HUP",
        'cat > "$request" <<\'QUARTO_MAIL_REQUEST\'',
        payload,
        "QUARTO_MAIL_REQUEST",
        f"gog --account {shlex.quote(manifest['account'])} api call gmail v1 {method} \\",
        f"  --params {shlex.quote(json.dumps(params, separators=(',', ':')))} \\",
        '  --body @"$request" --allow-write --force --no-input',
        "",
    ])


def build(bundle: Path) -> str:
    manifest = mime.read_manifest(bundle)
    raw = (bundle / "message.eml").read_bytes()
    request = json.loads((bundle / "gmail-request.json").read_text(encoding="utf-8"))
    if mime.decode_base64url(request["raw"]) != raw:
        raise ValueError("finalized message and Gmail request differ; render again")
    markdown = preview(raw, manifest)
    script = Path(manifest["source"]).with_suffix(".send.sh")
    mime.atomic_write(script, delivery_script(manifest, request).encode("utf-8"), mode=0o600)
    return markdown


def main() -> None:
    bundle = Path(sys.argv[1])
    try:
        print(build(bundle), end="")
    except (OSError, ValueError, KeyError, TypeError) as error:
        mime.remove_artifacts(bundle)
        raise SystemExit(f"quarto-mail: {error}") from error


if __name__ == "__main__":
    main()
