"""Internal mail-gog writer: emit a Markdown preview and a frozen delivery script."""

from __future__ import annotations

import json
import mimetypes
import shlex
import sys
from email.parser import BytesParser
from email.policy import default
from pathlib import Path
from typing import Any

import mime

# An instance uses Python's built-in mappings, not the host's MIME database.
MIME_TYPES = mimetypes.MimeTypes(filenames=())
ATTACHMENT_LABELS = {
    "application/octet-stream": "Binary",
    "image/jpeg": "JPEG",
}


def attachment_type(content_type: str) -> str:
    if label := ATTACHMENT_LABELS.get(content_type):
        return label
    if extension := MIME_TYPES.guess_extension(content_type):
        return extension.lstrip(".").upper()
    return content_type


def preview_value(value: str) -> str:
    # Every metadata row must remain one line, including inside a Markdown fence.
    return " ".join(value.split())


def attachment_size(size: int) -> str:
    for divisor, unit in ((1000**4, "TB"), (1000**3, "GB"), (1000**2, "MB"), (1000, "KB")):
        if size >= divisor:
            return f"{size / divisor:.1f}".removesuffix(".0") + f" {unit}"
    return f"{size} B"


def preview(raw: bytes, manifest: dict[str, Any]) -> str:
    message = BytesParser(policy=default).parsebytes(raw)
    lines = ["≡ " + preview_value(str(message.get("Subject", "(no subject)")))]
    senders = message["From"].addresses
    if message.get("Reply-To"):
        replies = message["Reply-To"].addresses
        if {address.addr_spec for address in replies} != {address.addr_spec for address in senders}:
            lines.extend("↪ " + preview_value(str(address)) + " · reply-to" for address in replies)
    if manifest.get("delivery") == "draft":
        delivery = "Update draft " + manifest["draft_id"] if manifest.get("draft_id") else "Create draft"
        lines.append("◇ " + preview_value(delivery))
    recipients = []
    for name, glyph, suffix in (("To", "→", ""), ("Cc", "⇢", " Ⓒ"), ("Bcc", "◌", " Ⓑ")):
        if message.get(name):
            recipients.extend(
                f"{glyph} " + preview_value(str(address)) + suffix
                for address in message[name].addresses
            )
    attachments = []
    for part in message.walk():
        if part.is_multipart() or part.get_content_disposition() not in ("attachment", "inline"):
            continue
        size = len(part.get_payload(decode=True) or b"")
        name = preview_value(part.get_filename() or "Unnamed attachment")
        content_type = part.get_content_type()
        label = preview_value(attachment_type(content_type))
        suffix = " · inline" if part.get_content_disposition() == "inline" else ""
        attachments.append(f"⊕ {name} · {label} · {attachment_size(size)}{suffix}")
    body = mime.body_content(message, "plain")
    if body is None:
        raise ValueError("the finalized message has no plain-text preview")
    envelope = "\n│\n".join("\n".join(group) for group in (lines, recipients, attachments) if group)
    return "```text\n" + envelope + "\n```\n\n---\n\n" + body


def delivery_script(manifest: dict[str, Any], request: dict[str, Any]) -> str:
    method = "gmail.users.messages.send"
    params = {"userId": "me"}
    body = request
    if manifest.get("delivery") == "draft":
        method = "gmail.users.drafts.create"
        body = {"message": request}
        if manifest.get("draft_id"):
            method = "gmail.users.drafts.update"
            params["id"] = manifest["draft_id"]
    # A single-line JSON payload cannot collide with the heredoc terminator.
    payload = json.dumps(body, ensure_ascii=True, separators=(",", ":"))
    return "\n".join([
        "#!/bin/sh",
        "# Generated by Quarto Mail. Running this script performs the configured delivery.",
        "set -eu",
        'if [ "$#" -ne 0 ]; then echo "Usage: sh MESSAGE.send.sh" >&2; exit 2; fi',
        "umask 077",
        'request=$(mktemp "${TMPDIR:-/tmp}/quarto-mail-send.XXXXXX")',
        "trap 'rm -f \"$request\"' EXIT",
        "trap 'exit 130' INT",
        "trap 'exit 143' TERM HUP",
        'cat > "$request" <<\'QUARTO_MAIL_REQUEST\'',
        payload,
        "QUARTO_MAIL_REQUEST",
        f"gog --account {shlex.quote(manifest['account'])} api call gmail v1 {method} \\",
        f"  --params {shlex.quote(json.dumps(params, separators=(',', ':')))} \\",
        '  --body @"$request" --allow-write --force --no-input',
        "",
    ])


def build(bundle: Path) -> str:
    manifest = mime.read_manifest(bundle)
    raw = (bundle / "message.eml").read_bytes()
    request = json.loads((bundle / "gmail-request.json").read_text(encoding="utf-8"))
    if mime.decode_base64url(request["raw"]) != raw:
        raise ValueError("finalized message and Gmail request differ; render again")
    markdown = preview(raw, manifest)
    script = Path(manifest["source"]).with_suffix(".send.sh")
    mime.atomic_write(script, delivery_script(manifest, request).encode("utf-8"), mode=0o600)
    return markdown


def main() -> None:
    bundle = Path(sys.argv[1])
    try:
        print(build(bundle), end="")
    except (OSError, ValueError, KeyError, TypeError) as error:
        mime.remove_artifacts(bundle)
        raise SystemExit(f"quarto-mail: {error}") from error


if __name__ == "__main__":
    main()
